# version: "3.8"
services:
  nodejs:
    container_name: nodejs_app
    build: .
    image: nodejs_app:latest
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./:/app
    command: bash -c "yarn install && yarn start"
    networks:
      - express
    # command: npm start
  mysql:
    container_name: mysql
    image: mysql:8
    # restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - express
  adminer:
    container_name: adminer
    image: adminer
    depends_on:
      - mysql
    ports:
      - ${ADMINER_PORT}:8080
    # restart: always
    networks:
      - express
networks:
  express:
    driver: bridge
volumes:
  mysqldata:
    driver: local
