# version: "3.8"
services:
  nodejs:
    container_name: nodejs_app
    build: .
    image: nodejs_app:latest
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: bash -c "yarn install && yarn start"
    networks:
      - express
    # command: npm start
  mysql:
    container_name: mysql
    image: mysql:8
    # restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - express
  adminer:
    container_name: adminer
    image: adminer
    depends_on:
      - mysql
    ports:
      - 8080:8080
    # restart: always
    networks:
      - express
networks:
  express:
    driver: bridge
volumes:
  mysqldata:
    driver: local
